### ISSUE TITLE
macOS 10.15触摸板无法使用

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-Catalina-Preview#2]
从10.14.6升级到10.15后触摸板用不了；

**Comment by LeLunZ** [comment]
`sudo kextcache -i /`

**Comment by BillTaozi** [comment]
运行了，但是出现一些提示
Last login: Sun Sep 22 07:42:12 on console
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
billtaozideMacBook-Pro:~ billtaozi$ sudo kextcache -i /
Password:
KernelCache ID: B25408131E2BF1D8E770D4D1067465B8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/kext_tools/kext_tools-623.11.1.180.1/rosp_staging.m.95: Error creating script /private/var/install/shove_kernels: 17 (File exists)
symlink("../../../PrelinkedKernels/prelinkedkernel", "/Library/Apple/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 2 (No such file or directory)
billtaozideMacBook-Pro:~ billtaozi$ 
然后无效，而且Final cut pro 闪退

**Comment by LeLunZ** [comment]
Seems like after Beta 6 some changes happend. Try running this: 


mount -uw /

sudo rm /private/var/install/shove_kernels
sudo touch /System/Library/Extensions && sudo kextcache -update-volume / -Installer

**Comment by LeLunZ** [comment]
If this is not working try:


touch /Volumes/Catalina/System/Library/Extensions/ && kextcache -u /Volumes/Catalina

**Comment by jardenliu** [comment]
重新更新配置
